# Generated by Django 4.0.5 on 2022-07-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=200, null=True)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('link', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Smiles', 'Smiles'), ('Laughter', 'Laughter'), ('Crazy', 'Crazy'), ('Food', 'Food'), ('Outside', 'Outside')], max_length=200, null=True)),
            ],
            options={
                'unique_together': {('title', 'link')},
            },
        ),
    ]
