# Generated by Django 4.0.5 on 2022-12-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.CharField(blank=True, choices=[('Highly recommended', 'Highly recommended'), ('Fun for the whole family', 'Fun for the whole family')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
